#!/bin/bash

if [[ $BASH_SOURCE = */* ]]; then
    cd -- "${BASH_SOURCE%/*}/" || exit
fi

if ! socat /dev/null "/var/run/user/$UID/quick-find/activate"; then
   echo "Couldn't connect. Starting quickfind."
   ./quickfind &
fi	
